### ISSUE TITLE
关于GAT的结果

### ISSUE THREAD

**Issue by Riting-Xia** [LirongWu/GraphMixup#1]
您好，我在做对比实验的时候发现编码器为GAT的结果很差，请问是什么原因？

**Comment by LirongWu** [comment]
您可以先确认一下python的packages版本是否一致。不同的硬件平台上，package版本不同，会使得模型初始化差异很大，对GAT这类编码器的影响较大。建议您可以在自己的平台上搜索一下最优的超参数组合，使得原始GAT的性能与标准实验的结果一致，再以GAT为编码器做原文的对比试验。
